from django.urls import path

from game.quest_builder_views import (
    choice_create,
    choice_delete,
    choice_panel,
    choice_requirements_save,
    choice_save,
    quest_builder_canvas,
    quest_builder_list,
    quest_validate,
    scene_combat_save,
    scene_contacts_save,
    scene_create,
    scene_delete,
    scene_gang_standings_save,
    scene_items_save,
    scene_move,
    scene_panel,
    scene_save,
)


def build_quest_builder_urls(admin_site):
    return [
        path(
            "quest-builder/",
            admin_site.admin_view(quest_builder_list),
            name="quest_builder_list",
        ),
        path(
            "quest-builder/<int:quest_id>/",
            admin_site.admin_view(quest_builder_canvas),
            name="quest_builder_canvas",
        ),
        path(
            "quest-builder/<int:quest_id>/validate/",
            admin_site.admin_view(quest_validate),
            name="quest_builder_validate",
        ),
        path(
            "quest-builder/<int:quest_id>/scene/new/",
            admin_site.admin_view(scene_panel),
            name="quest_builder_scene_panel_new",
        ),
        path(
            "quest-builder/<int:quest_id>/scene/<int:scene_id>/",
            admin_site.admin_view(scene_panel),
            name="quest_builder_scene_panel",
        ),
        path(
            "quest-builder/<int:quest_id>/scene/<int:scene_id>/save/",
            admin_site.admin_view(scene_save),
            name="quest_builder_scene_save",
        ),
        path(
            "quest-builder/<int:quest_id>/scene/create/",
            admin_site.admin_view(scene_create),
            name="quest_builder_scene_create",
        ),
        path(
            "quest-builder/<int:quest_id>/scene/<int:scene_id>/delete/",
            admin_site.admin_view(scene_delete),
            name="quest_builder_scene_delete",
        ),
        path(
            "quest-builder/<int:quest_id>/scene/<int:scene_id>/move/",
            admin_site.admin_view(scene_move),
            name="quest_builder_scene_move",
        ),
        path(
            "quest-builder/<int:quest_id>/choice/new/<int:source_scene_id>/",
            admin_site.admin_view(choice_panel),
            name="quest_builder_choice_panel_new",
        ),
        path(
            "quest-builder/<int:quest_id>/choice/create/",
            admin_site.admin_view(choice_create),
            name="quest_builder_choice_create",
        ),
        path(
            "quest-builder/<int:quest_id>/choice/<int:choice_id>/",
            admin_site.admin_view(choice_panel),
            name="quest_builder_choice_panel",
        ),
        path(
            "quest-builder/<int:quest_id>/choice/<int:choice_id>/save/",
            admin_site.admin_view(choice_save),
            name="quest_builder_choice_save",
        ),
        path(
            "quest-builder/<int:quest_id>/choice/<int:choice_id>/delete/",
            admin_site.admin_view(choice_delete),
            name="quest_builder_choice_delete",
        ),
        path(
            "quest-builder/<int:quest_id>/scene/<int:scene_id>/items/save/",
            admin_site.admin_view(scene_items_save),
            name="quest_builder_scene_items_save",
        ),
        path(
            "quest-builder/<int:quest_id>/scene/<int:scene_id>/contacts/save/",
            admin_site.admin_view(scene_contacts_save),
            name="quest_builder_scene_contacts_save",
        ),
        path(
            "quest-builder/<int:quest_id>/scene/<int:scene_id>/gang-standings/save/",
            admin_site.admin_view(scene_gang_standings_save),
            name="quest_builder_scene_gang_standings_save",
        ),
        path(
            "quest-builder/<int:quest_id>/scene/<int:scene_id>/combat/save/",
            admin_site.admin_view(scene_combat_save),
            name="quest_builder_scene_combat_save",
        ),
        path(
            "quest-builder/<int:quest_id>/choice/<int:choice_id>/requirements/save/",
            admin_site.admin_view(choice_requirements_save),
            name="quest_builder_choice_requirements_save",
        ),
    ]
