# Generated by Django 6.0.4 on 2026-05-09 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=200)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Enemy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('max_hp', models.IntegerField(default=10)),
                ('attack_modifier', models.IntegerField(default=0)),
                ('defense', models.IntegerField(default=8)),
                ('damage_min', models.IntegerField(default=1)),
                ('damage_max', models.IntegerField(default=4)),
            ],
        ),
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=100, unique=True)),
                ('turn_counter', models.PositiveIntegerField(default=0)),
                ('flags', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('is_consumable', models.BooleanField(default=False)),
                ('effect_type', models.CharField(blank=True, choices=[('heal_hp', 'Heal HP'), ('add_stat', 'Permanently increase a stat')], max_length=20)),
                ('effect_stat', models.CharField(blank=True, max_length=20)),
                ('effect_value', models.IntegerField(default=0)),
                ('passive_stat', models.CharField(blank=True, max_length=20)),
                ('passive_value', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Territory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('cash_per_turn', models.IntegerField(default=0)),
                ('heat_per_turn', models.IntegerField(default=0)),
                ('rep_per_turn', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='EventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField()),
                ('batch_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log', to='game.gamesession')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='CombatState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enemy_hp', models.IntegerField()),
                ('turn_number', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('pending_victory', models.BooleanField(default=False)),
                ('pending_enemy_roll', models.IntegerField(blank=True, null=True)),
                ('pending_enemy_total', models.IntegerField(blank=True, null=True)),
                ('pending_enemy_hit', models.BooleanField(blank=True, null=True)),
                ('pending_enemy_damage', models.IntegerField(blank=True, null=True)),
                ('enemy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.enemy')),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='combat_state', to='game.gamesession')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strength', models.IntegerField(default=5)),
                ('agility', models.IntegerField(default=5)),
                ('intellect', models.IntegerField(default=5)),
                ('charisma', models.IntegerField(default=5)),
                ('hp', models.IntegerField(default=20)),
                ('max_hp', models.IntegerField(default=20)),
                ('level', models.IntegerField(default=1)),
                ('experience', models.IntegerField(default=0)),
                ('stat_points', models.IntegerField(default=0)),
                ('stat_points_awarded', models.IntegerField(default=0)),
                ('cash', models.IntegerField(default=0)),
                ('heat', models.IntegerField(default=0)),
                ('rep', models.IntegerField(default=0)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='game.gamesession')),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('property_type', models.CharField(choices=[('safehouse', 'Safe House'), ('business', 'Business')], max_length=20)),
                ('cash_per_turn', models.IntegerField(default=0)),
                ('heat_per_turn', models.IntegerField(default=0)),
                ('rep_per_turn', models.IntegerField(default=0)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('property_type__in', ['safehouse', 'business'])), name='property_type_no_territory')],
            },
        ),
        migrations.CreateModel(
            name='PlayerProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='game.gamesession')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.property')),
            ],
        ),
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('is_unlocked', models.BooleanField(default=True)),
                ('arc_order', models.IntegerField(blank=True, default=0, null=True)),
                ('is_repeatable', models.BooleanField(default=False, help_text="If True, this quest's entry choice re-appears after completion.")),
                ('arc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quests', to='game.arc')),
            ],
            options={
                'ordering': ['arc_order'],
            },
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition_type', models.CharField(choices=[('stat_gte', 'Stat >= value'), ('stat_lte', 'Stat <= value'), ('has_item', 'Has item in inventory'), ('missing_item', 'Does not have item'), ('quest_completed', 'Quest completed'), ('quest_not_done', 'Quest not completed'), ('quest_ending', 'Quest completed with specific ending'), ('level_gte', 'Player level >= value'), ('xp_gte', 'Player XP >= value'), ('has_flag', 'Flag is set'), ('missing_flag', 'Flag is not set'), ('has_contact', 'Has contact'), ('missing_contact', 'Does not have contact')], max_length=50)),
                ('flag_name', models.CharField(blank=True, max_length=100)),
                ('stat_name', models.CharField(blank=True, max_length=50)),
                ('stat_value', models.IntegerField(blank=True, default=0)),
                ('required_ending_type', models.CharField(blank=True, max_length=20)),
                ('required_contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='game.contact')),
                ('required_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='game.item')),
                ('required_quest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='game.quest')),
            ],
        ),
        migrations.CreateModel(
            name='RequirementGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('logic', models.CharField(choices=[('all', 'All must pass (AND)'), ('any', 'Any one must pass (OR)')], default='all', max_length=10)),
                ('scope_type', models.CharField(blank=True, max_length=50, null=True)),
                ('scope_key', models.CharField(blank=True, max_length=255, null=True)),
                ('group_key', models.CharField(blank=True, max_length=255, null=True)),
                ('requirements', models.ManyToManyField(related_name='groups', to='game.requirement')),
            ],
        ),
        migrations.AddField(
            model_name='quest',
            name='requirements',
            field=models.ManyToManyField(blank=True, related_name='gated_quests', to='game.requirementgroup'),
        ),
        migrations.CreateModel(
            name='Scene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(unique=True)),
                ('scene_type', models.CharField(choices=[('normal', 'Normal'), ('hub', 'Hub'), ('combat', 'Combat'), ('ending', 'Ending')], default='normal', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('order', models.IntegerField(default=0)),
                ('requires_roll', models.BooleanField(default=False)),
                ('roll_stat', models.CharField(blank=True, choices=[('', '---'), ('strength', 'strength'), ('agility', 'agility'), ('intellect', 'intellect'), ('charisma', 'charisma')], max_length=50)),
                ('roll_difficulty', models.IntegerField(default=10)),
                ('ending_type', models.CharField(blank=True, choices=[('victory', 'Victory'), ('defeat', 'Defeat'), ('neutral', 'Neutral')], max_length=20)),
                ('ambient_sound', models.CharField(blank=True, max_length=100)),
                ('canvas_x', models.IntegerField(default=0)),
                ('canvas_y', models.IntegerField(default=0)),
                ('cash_change', models.IntegerField(default=0, help_text='Cash delta when arriving at this scene.')),
                ('rep_change', models.IntegerField(default=0, help_text='Reputation delta when arriving at this scene.')),
                ('heat_change', models.IntegerField(default=0, help_text='Heat change when arriving at this scene (can be negative).')),
                ('consume_item', models.ForeignKey(blank=True, help_text='If set, this item is removed from inventory when the player arrives at this scene.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consumed_by_scenes', to='game.item')),
                ('lose_property', models.ForeignKey(blank=True, help_text='Property lost when arriving at this scene.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='game.property')),
                ('quest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scenes', to='game.quest')),
                ('receive_property', models.ForeignKey(blank=True, help_text='Property awarded when arriving at this scene.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='game.property')),
                ('discover_territory', models.ForeignKey(blank=True, help_text='Territory discovered when arriving at this scene.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='game.territory')),
                ('lose_territory', models.ForeignKey(blank=True, help_text='Territory lost when arriving at this scene.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='game.territory')),
                ('receive_territory', models.ForeignKey(blank=True, help_text='Territory awarded when arriving at this scene.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='game.territory')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='quest',
            name='entrance_scene',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='game.scene'),
        ),
        migrations.AddField(
            model_name='quest',
            name='hub_scenes',
            field=models.ManyToManyField(blank=True, help_text='Hub scenes whose notice board lists this quest.', limit_choices_to={'scene_type': 'hub'}, related_name='posted_quests', to='game.scene'),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='current_scene',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.scene'),
        ),
        migrations.CreateModel(
            name='CombatEncounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('victory_arrival_flavor', models.TextField(blank=True)),
                ('defeat_arrival_flavor', models.TextField(blank=True)),
                ('enemy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encounters', to='game.enemy')),
                ('defeat_scene', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='game.scene')),
                ('scene', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='combat_encounter', to='game.scene')),
                ('victory_scene', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='game.scene')),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=300)),
                ('order', models.IntegerField(default=0)),
                ('arrival_flavor', models.TextField(blank=True)),
                ('failure_arrival_flavor', models.TextField(blank=True, help_text='Logged instead of arrival_flavor when a roll fails.')),
                ('set_flag_name', models.CharField(blank=True, help_text='If set, this flag is set on the session when this choice is taken. Use a registered key or supported dynamic pattern.', max_length=100)),
                ('clear_flag_name', models.CharField(blank=True, help_text='If set, this flag is cleared from the session when this choice is taken. Use a registered key or supported dynamic pattern.', max_length=100)),
                ('requirements', models.ManyToManyField(blank=True, related_name='gated_choices', to='game.requirementgroup')),
                ('failure_scene', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='game.scene')),
                ('scene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='game.scene')),
                ('success_scene', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='game.scene')),
                ('target_scene', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='game.scene')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SceneContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('gain', 'Gain'), ('lose', 'Lose')], default='gain', max_length=10)),
                ('award_once', models.BooleanField(default=True, help_text='If True, gaining this contact is skipped when the player already has it.')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='found_in', to='game.contact')),
                ('scene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scene_contacts', to='game.scene')),
            ],
        ),
        migrations.CreateModel(
            name='SceneGangStanding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standing_change', models.IntegerField(default=0)),
                ('gang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scene_standing_changes', to='game.gang')),
                ('scene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scene_gang_standings', to='game.scene')),
            ],
        ),
        migrations.CreateModel(
            name='SceneItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('award_once', models.BooleanField(default=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='found_in', to='game.item')),
                ('scene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scene_items', to='game.scene')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerTerritory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='territories', to='game.gamesession')),
                ('territory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.territory')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerDiscoveredTerritory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discovered_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discovered_territories', to='game.gamesession')),
                ('territory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discovered_by', to='game.territory')),
            ],
            options={
                'ordering': ['discovered_at'],
            },
        ),
        migrations.CreateModel(
            name='PlayerContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acquired_at', models.DateTimeField(auto_now_add=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='held_by', to='game.contact')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='game.gamesession')),
            ],
            options={
                'ordering': ['acquired_at'],
                'constraints': [models.UniqueConstraint(fields=('session', 'contact'), name='uq_playercontact_session_contact')],
            },
        ),
        migrations.CreateModel(
            name='PlayerGangStanding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standing', models.IntegerField(default=0)),
                ('gang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_standings', to='game.gang')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gang_standings', to='game.gamesession')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('session', 'gang'), name='uq_playergangstanding_session_gang')],
            },
        ),
        migrations.CreateModel(
            name='PlayerInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('acquired_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='held_by', to='game.item')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='game.gamesession')),
            ],
            options={
                'ordering': ['acquired_at'],
                'constraints': [models.UniqueConstraint(fields=('session', 'item'), name='uq_playerinventory_session_item')],
            },
        ),
        migrations.CreateModel(
            name='CompletedQuest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ending_type', models.CharField(max_length=20)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completed_quests', to='game.gamesession')),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.quest')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('session', 'quest'), name='uq_completedquest_session_quest')],
            },
        ),
        migrations.AddConstraint(
            model_name='requirementgroup',
            constraint=models.UniqueConstraint(condition=models.Q(('scope_type__isnull', False), ('scope_key__isnull', False), ('group_key__isnull', False)), fields=('scope_type', 'scope_key', 'group_key'), name='uq_requirement_group_scoped_identity'),
        ),
        migrations.AddConstraint(
            model_name='scenegangstanding',
            constraint=models.UniqueConstraint(fields=('scene', 'gang'), name='uq_scenegangstanding_scene_gang'),
        ),
        migrations.AddConstraint(
            model_name='playerdiscoveredterritory',
            constraint=models.UniqueConstraint(fields=('session', 'territory'), name='uq_playerdiscoveredterritory_session_territory'),
        ),
    ]
