# Generated by Django 6.0.4 on 2026-04-09 22:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=200)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Enemy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('max_hp', models.IntegerField(default=10)),
                ('attack_modifier', models.IntegerField(default=0)),
                ('defense', models.IntegerField(default=8)),
                ('damage_min', models.IntegerField(default=1)),
                ('damage_max', models.IntegerField(default=4)),
            ],
        ),
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('is_consumable', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='EventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField()),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log', to='game.gamesession')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='CombatState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enemy_hp', models.IntegerField()),
                ('turn_number', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('enemy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.enemy')),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='combat_state', to='game.gamesession')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strength', models.IntegerField(default=5)),
                ('agility', models.IntegerField(default=5)),
                ('intellect', models.IntegerField(default=5)),
                ('charisma', models.IntegerField(default=5)),
                ('hp', models.IntegerField(default=20)),
                ('max_hp', models.IntegerField(default=20)),
                ('level', models.IntegerField(default=1)),
                ('experience', models.IntegerField(default=0)),
                ('stat_points', models.IntegerField(default=0)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='game.gamesession')),
            ],
        ),
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('is_unlocked', models.BooleanField(default=True)),
                ('arc_order', models.IntegerField(default=0)),
                ('arc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quests', to='game.arc')),
            ],
            options={
                'ordering': ['arc_order'],
            },
        ),
        migrations.CreateModel(
            name='CompletedQuest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ending_type', models.CharField(max_length=20)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completed_quests', to='game.gamesession')),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.quest')),
            ],
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition_type', models.CharField(choices=[('stat_gte', 'Stat >= value'), ('stat_lte', 'Stat <= value'), ('has_item', 'Has item in inventory'), ('missing_item', 'Does not have item'), ('quest_completed', 'Quest completed'), ('quest_not_done', 'Quest not completed'), ('quest_ending', 'Quest completed with specific ending'), ('level_gte', 'Player level >= value'), ('xp_gte', 'Player XP >= value')], max_length=50)),
                ('stat_name', models.CharField(blank=True, max_length=50)),
                ('stat_value', models.IntegerField(default=0)),
                ('required_ending_type', models.CharField(blank=True, max_length=20)),
                ('required_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='game.item')),
                ('required_quest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='game.quest')),
            ],
        ),
        migrations.CreateModel(
            name='RequirementGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('logic', models.CharField(choices=[('all', 'All must pass (AND)'), ('any', 'Any one must pass (OR)')], default='all', max_length=10)),
                ('requirements', models.ManyToManyField(related_name='groups', to='game.requirement')),
            ],
        ),
        migrations.CreateModel(
            name='Scene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(unique=True)),
                ('is_hub', models.BooleanField(default=False)),
                ('is_combat', models.BooleanField(default=False)),
                ('is_ending', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('order', models.IntegerField(default=0)),
                ('requires_roll', models.BooleanField(default=False)),
                ('roll_stat', models.CharField(blank=True, max_length=50)),
                ('roll_difficulty', models.IntegerField(default=10)),
                ('ending_type', models.CharField(blank=True, choices=[('victory', 'Victory'), ('defeat', 'Defeat'), ('neutral', 'Neutral')], max_length=20)),
                ('ambient_sound', models.CharField(blank=True, max_length=100)),
                ('quest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scenes', to='game.quest')),
                ('requirements', models.ManyToManyField(blank=True, related_name='gated_scenes', to='game.requirementgroup')),
            ],
            options={
                'ordering': ['quest', 'order'],
            },
        ),
        migrations.AddField(
            model_name='quest',
            name='entrance_scene',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='game.scene'),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='current_scene',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.scene'),
        ),
        migrations.AddField(
            model_name='enemy',
            name='defeat_scene',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='game.scene'),
        ),
        migrations.AddField(
            model_name='enemy',
            name='victory_scene',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='game.scene'),
        ),
        migrations.CreateModel(
            name='CombatEncounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enemy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encounters', to='game.enemy')),
                ('scene', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='combat_encounter', to='game.scene')),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=300)),
                ('order', models.IntegerField(default=0)),
                ('arrival_flavor', models.TextField(blank=True)),
                ('consume_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consumed_by_choices', to='game.item')),
                ('requirements', models.ManyToManyField(blank=True, related_name='gated_choices', to='game.requirementgroup')),
                ('failure_scene', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='game.scene')),
                ('scene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='game.scene')),
                ('success_scene', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='game.scene')),
                ('target_scene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='game.scene')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SceneItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('award_once', models.BooleanField(default=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='found_in', to='game.item')),
                ('scene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scene_items', to='game.scene')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('acquired_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='held_by', to='game.item')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='game.gamesession')),
            ],
            options={
                'ordering': ['acquired_at'],
                'unique_together': {('session', 'item')},
            },
        ),
    ]
