# Generated by Django 6.0.4 on 2026-04-09 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='required_minimum',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='choice',
            name='required_stat',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
