# Generated by Django 6.0.4 on 2026-04-09 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_choice_required_minimum_choice_required_stat'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='required_minimum',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quest',
            name='required_quest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unlocks', to='game.quest'),
        ),
        migrations.AddField(
            model_name='quest',
            name='required_stat',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
