# Generated by Django 6.0.4 on 2026-04-11 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_quest_required_minimum_quest_required_quest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='effect_stat',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='item',
            name='effect_type',
            field=models.CharField(blank=True, choices=[('heal_hp', 'Heal HP'), ('add_stat', 'Permanently increase a stat')], max_length=20),
        ),
        migrations.AddField(
            model_name='item',
            name='effect_value',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='equip_slot',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='item',
            name='passive_stat',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='item',
            name='passive_value',
            field=models.IntegerField(default=0),
        ),
    ]
