# Generated by Django 6.0.4 on 2026-04-11 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_item_effect_stat_item_effect_type_item_effect_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='requirements',
            field=models.ManyToManyField(blank=True, related_name='gated_quests', to='game.requirementgroup'),
        ),
    ]
