# Generated by Django 6.0.4 on 2026-04-11 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_migrate_legacy_gates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='required_minimum',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='required_stat',
        ),
        migrations.RemoveField(
            model_name='quest',
            name='required_minimum',
        ),
        migrations.RemoveField(
            model_name='quest',
            name='required_quest',
        ),
        migrations.RemoveField(
            model_name='quest',
            name='required_stat',
        ),
    ]
