# Generated by Django 6.0.4 on 2026-04-11 17:38

from django.db import migrations, models



def migrate_data(apps, schema_editor):
    Scene = apps.get_model('game', 'Scene')
    for scene in Scene.objects.all():
        if getattr(scene, 'is_hub', False):
            scene.scene_type = 'hub'
        elif getattr(scene, 'is_combat', False):
            scene.scene_type = 'combat'
        elif getattr(scene, 'is_ending', False):
            scene.scene_type = 'ending'
        else:
            scene.scene_type = 'normal'
        scene.save()

class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_remove_legacy_gate_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='scene',
            name='scene_type',
            field=models.CharField(choices=[('normal', 'Normal'), ('hub', 'Hub'), ('combat', 'Combat'), ('ending', 'Ending')], default='normal', max_length=20),
        ),
        migrations.RunPython(migrate_data, reverse_code=migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='scene',
            name='is_combat',
        ),
        migrations.RemoveField(
            model_name='scene',
            name='is_ending',
        ),
        migrations.RemoveField(
            model_name='scene',
            name='is_hub',
        ),
    ]
