# Generated by Django 6.0.4 on 2026-04-12 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_replace_scene_flags'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='quest',
            field=models.ForeignKey(blank=True, help_text='If set, this choice starts the linked quest and is hidden once the quest is completed (unless the quest is repeatable).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entry_choices', to='game.quest'),
        ),
        migrations.AddField(
            model_name='quest',
            name='is_repeatable',
            field=models.BooleanField(default=False, help_text="If True, this quest's entry choice re-appears after completion."),
        ),
    ]
