# Generated by Django 6.0.4 on 2026-04-12 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_choice_quest_quest_is_repeatable'),
    ]

    operations = [
        migrations.CreateModel(
            name='SceneUnlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_scene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unlocks', to='game.scene')),
                ('requires_choice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggers_unlocks', to='game.choice')),
                ('requires_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='game.item')),
                ('unlocks_scene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unlocked_by', to='game.scene')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerSceneState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('locked', 'Locked'), ('available', 'Available'), ('completed', 'Completed')], default='available', max_length=20)),
                ('scene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_states', to='game.scene')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scene_states', to='game.gamesession')),
            ],
            options={
                'unique_together': {('session', 'scene')},
            },
        ),
    ]
