# Generated by Django 6.0.4 on 2026-04-12 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_sceneunlock_playerscenestate'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerstats',
            name='cash',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerstats',
            name='heat',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerstats',
            name='rep',
            field=models.IntegerField(default=0),
        ),
    ]
