# Generated by Django 6.0.4 on 2026-04-12 21:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_playerstats_cash_playerstats_heat_playerstats_rep'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('property_type', models.CharField(choices=[('safehouse', 'Safe House'), ('business', 'Business'), ('territory', 'Territory')], max_length=20)),
                ('income_per_turn', models.IntegerField(default=0)),
                ('heat_reduction', models.IntegerField(default=0)),
                ('rep_bonus', models.IntegerField(default=0)),
                ('is_contestable', models.BooleanField(default=False)),
                ('resolution_scene', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='game.scene')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_contested', models.BooleanField(default=False)),
                ('upgrade_tier', models.IntegerField(default=1)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='game.gamesession')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.property')),
            ],
        ),
        migrations.CreateModel(
            name='RivalClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='game.playerproperty')),
                ('resolution_scene', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='game.scene')),
            ],
        ),
    ]
