# Generated by Django 6.0.4 on 2026-04-13 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0013_remove_item_equip_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='flags',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
