# Generated by Django 6.0.4 on 2026-04-13 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0014_add_flags_to_gamesession'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='flag_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='condition_type',
            field=models.CharField(choices=[('stat_gte', 'Stat >= value'), ('stat_lte', 'Stat <= value'), ('has_item', 'Has item in inventory'), ('missing_item', 'Does not have item'), ('quest_completed', 'Quest completed'), ('quest_not_done', 'Quest not completed'), ('quest_ending', 'Quest completed with specific ending'), ('level_gte', 'Player level >= value'), ('xp_gte', 'Player XP >= value'), ('has_flag', 'Flag is set'), ('missing_flag', 'Flag is not set')], max_length=50),
        ),
    ]
