# Generated by Django 6.0.4 on 2026-04-13 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0015_add_flag_name_to_requirement'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='clear_flag_name',
            field=models.CharField(blank=True, help_text='If set, this flag is cleared from the session when this choice is taken.', max_length=100),
        ),
        migrations.AddField(
            model_name='choice',
            name='set_flag_name',
            field=models.CharField(blank=True, help_text='If set, this flag is set on the session when this choice is taken.', max_length=100),
        ),
    ]
