# Generated by Django 6.0.4 on 2026-04-13 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0016_add_flag_effects_to_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirement',
            name='stat_value',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
