# Generated by Django 6.0.4 on 2026-04-13 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0017_alter_requirement_stat_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='scene',
            name='canvas_x',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scene',
            name='canvas_y',
            field=models.IntegerField(default=0),
        ),
    ]
