# Generated by Django 6.0.4 on 2026-04-13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0018_scene_canvas_x_scene_canvas_y'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='target_scene',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='+',
                to='game.scene',
            ),
        ),
    ]
