# Generated by Django 6.0.4 on 2026-04-14 23:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0019_alter_choice_target_scene'),
    ]

    operations = [
        migrations.AddField(
            model_name='combatencounter',
            name='defeat_scene',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='game.scene'),
        ),
        migrations.AddField(
            model_name='combatencounter',
            name='victory_scene',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='game.scene'),
        ),
    ]
