# Generated by Django 6.0.4 on 2026-04-18 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0020_combatencounter_victory_defeat_scenes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scene',
            name='requirements',
        ),
    ]
