# Generated by Django 6.0.4 on 2026-04-18 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0022_add_quest_hub_scenes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PlayerSceneState',
        ),
    ]
