# Generated by Django 6.0.4 on 2026-04-18 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0025_remove_quest_fk_from_scene_choice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scene',
            options={'ordering': ['order']},
        ),
        migrations.DeleteModel(
            name='SceneUnlock',
        ),
    ]
