# Generated by Django 6.0.4 on 2026-04-18 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0026_remove_sceneunlock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quest',
            name='entry_choices',
        ),
    ]
