# Generated by Django 6.0.4 on 2026-04-18 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0027_remove_quest_entry_choices'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='completedquest',
            unique_together={('session', 'quest')},
        ),
    ]
