# Generated by Django 6.0.4 on 2026-04-18 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0028_alter_completedquest_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerproperty',
            name='upgrade_tier',
        ),
        migrations.AlterField(
            model_name='scene',
            name='roll_stat',
            field=models.CharField(blank=True, choices=[('', '---'), ('strength', 'strength'), ('agility', 'agility'), ('intellect', 'intellect'), ('charisma', 'charisma')], max_length=50),
        ),
    ]
