# Generated by Django 6.0.4 on 2026-04-18 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0029_remove_playerproperty_upgrade_tier_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enemy',
            name='defeat_scene',
        ),
        migrations.RemoveField(
            model_name='enemy',
            name='victory_scene',
        ),
    ]
