# Generated by Django 6.0.4 on 2026-04-18 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0030_remove_enemy_defeat_scene_remove_enemy_victory_scene'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='cash_reward',
            field=models.IntegerField(default=0, help_text='Cash awarded when this choice is taken.'),
        ),
        migrations.AddField(
            model_name='choice',
            name='rep_reward',
            field=models.IntegerField(default=0, help_text='Reputation awarded when this choice is taken.'),
        ),
        migrations.AddField(
            model_name='scene',
            name='cash_reward',
            field=models.IntegerField(default=0, help_text='Cash awarded when arriving at this scene.'),
        ),
        migrations.AddField(
            model_name='scene',
            name='rep_reward',
            field=models.IntegerField(default=0, help_text='Reputation awarded when arriving at this scene.'),
        ),
    ]
