# Generated by Django 6.0.4 on 2026-04-18 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0031_choice_cash_reward_choice_rep_reward_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='cash_reward',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='rep_reward',
        ),
    ]
