# Generated by Django 6.0.4 on 2026-04-18 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0032_remove_choice_cash_reward_remove_choice_rep_reward'),
    ]

    operations = [
        migrations.AddField(
            model_name='scene',
            name='heat_change',
            field=models.IntegerField(default=0, help_text='Heat change when arriving at this scene (can be negative).'),
        ),
        migrations.AddField(
            model_name='scene',
            name='lose_property',
            field=models.ForeignKey(blank=True, help_text='Property lost when arriving at this scene.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='game.property'),
        ),
        migrations.AddField(
            model_name='scene',
            name='receive_property',
            field=models.ForeignKey(blank=True, help_text='Property awarded when arriving at this scene.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='game.property'),
        ),
    ]
