# Generated by Django 6.0.4 on 2026-04-18 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0033_scene_heat_change_scene_lose_property_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='failure_arrival_flavor',
            field=models.TextField(blank=True, help_text='Logged instead of arrival_flavor when a roll fails.'),
        ),
        migrations.AddField(
            model_name='combatencounter',
            name='defeat_arrival_flavor',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='combatencounter',
            name='victory_arrival_flavor',
            field=models.TextField(blank=True),
        ),
    ]
