# Generated by Django 6.0.4 on 2026-04-19 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0036_standardize_field_suffixes'),
    ]

    operations = [
        migrations.AddField(
            model_name='combatstate',
            name='pending_victory',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='scene',
            name='cash_change',
            field=models.IntegerField(default=0, help_text='Cash delta when arriving at this scene.'),
        ),
        migrations.AlterField(
            model_name='scene',
            name='rep_change',
            field=models.IntegerField(default=0, help_text='Reputation delta when arriving at this scene.'),
        ),
    ]
