# Generated by Django 6.0.4 on 2026-04-19 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0037_add_pending_victory_to_combatstate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='requirement',
            name='condition_type',
            field=models.CharField(choices=[('stat_gte', 'Stat >= value'), ('stat_lte', 'Stat <= value'), ('has_item', 'Has item in inventory'), ('missing_item', 'Does not have item'), ('quest_completed', 'Quest completed'), ('quest_not_done', 'Quest not completed'), ('quest_ending', 'Quest completed with specific ending'), ('level_gte', 'Player level >= value'), ('xp_gte', 'Player XP >= value'), ('has_flag', 'Flag is set'), ('missing_flag', 'Flag is not set'), ('has_contact', 'Has contact'), ('missing_contact', 'Does not have contact')], max_length=50),
        ),
        migrations.AddField(
            model_name='requirement',
            name='required_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='game.contact'),
        ),
        migrations.CreateModel(
            name='SceneContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('gain', 'Gain'), ('lose', 'Lose')], default='gain', max_length=10)),
                ('award_once', models.BooleanField(default=True, help_text='If True, gaining this contact is skipped when the player already has it.')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='found_in', to='game.contact')),
                ('scene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scene_contacts', to='game.scene')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acquired_at', models.DateTimeField(auto_now_add=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='held_by', to='game.contact')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='game.gamesession')),
            ],
            options={
                'ordering': ['acquired_at'],
                'unique_together': {('session', 'contact')},
            },
        ),
        migrations.CreateModel(
            name='PlayerGangStanding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standing', models.IntegerField(default=0)),
                ('gang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_standings', to='game.gang')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gang_standings', to='game.gamesession')),
            ],
            options={
                'unique_together': {('session', 'gang')},
            },
        ),
    ]
