# Generated by Django 6.0.4 on 2026-04-20 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0038_contact_gang_alter_requirement_condition_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arc',
            name='order',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
