# Generated by Django 6.0.4 on 2026-04-20 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0039_alter_arc_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arc',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='quest',
            name='arc_order',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
