# Generated by Django 6.0.4 on 2026-04-21 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0040_alter_arc_order_alter_quest_arc_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerstats',
            name='stat_points_awarded',
            field=models.IntegerField(default=0),
        ),
    ]
