# Generated by Django 6.0.4 on 2026-04-24 22:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0041_playerstats_stat_points_awarded'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='turn_counter',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('base_cooldown_turns', models.PositiveIntegerField(default=3)),
                ('base_cash_min', models.PositiveIntegerField(default=0)),
                ('base_cash_max', models.PositiveIntegerField(default=0)),
                ('base_heat', models.IntegerField(default=0)),
                ('base_rep', models.IntegerField(default=0)),
                ('recon_text_low', models.TextField(blank=True)),
                ('recon_text_mid', models.TextField(blank=True)),
                ('recon_text_high', models.TextField(blank=True)),
                ('district_hubs', models.ManyToManyField(blank=True, help_text='Hub scenes where this job target appears for recon.', limit_choices_to={'scene_type': 'hub'}, related_name='district_jobs', to='game.scene')),
                ('unlock_requirements', models.ManyToManyField(blank=True, related_name='gated_jobs', to='game.requirementgroup')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='ContactJobOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(unique=True)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('min_run_count', models.PositiveIntegerField(default=0)),
                ('required_flag', models.CharField(blank=True, max_length=100)),
                ('cooldown_turns', models.PositiveIntegerField(default=0)),
                ('first_meeting_text', models.TextField(blank=True)),
                ('standard_offer_text', models.TextField(blank=True)),
                ('nothing_available_text', models.TextField(blank=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_offers', to='game.contact')),
                ('scene', models.ForeignKey(blank=True, help_text='Hub scene where this contact can offer this job.', limit_choices_to={'scene_type': 'hub'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_job_offers', to='game.scene')),
                ('unlock_requirements', models.ManyToManyField(blank=True, related_name='gated_contact_job_offers', to='game.requirementgroup')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_offers', to='game.job')),
            ],
            options={
                'ordering': ['contact', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='JobApproach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(help_text="Approach key used for flags, e.g. 'alley' in approach_alley.")),
                ('label', models.CharField(max_length=200)),
                ('order', models.IntegerField(default=0)),
                ('min_recon_tier', models.CharField(choices=[('low', 'Low'), ('mid', 'Mid'), ('high', 'High')], default='low', max_length=10)),
                ('roll_stat', models.CharField(choices=[('strength', 'strength'), ('agility', 'agility'), ('intellect', 'intellect'), ('charisma', 'charisma')], max_length=50)),
                ('base_difficulty', models.IntegerField(default=10)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approaches', to='game.job')),
            ],
            options={
                'ordering': ['job', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='JobBeatVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beat_number', models.PositiveSmallIntegerField(choices=[(0, 'Beat 0 - Recon'), (1, 'Beat 1 - Approach'), (2, 'Beat 2 - Complication'), (3, 'Beat 3 - Resolution')])),
                ('key', models.SlugField()),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0)),
                ('requires_roll', models.BooleanField(default=False)),
                ('roll_stat', models.CharField(blank=True, choices=[('', '---'), ('strength', 'strength'), ('agility', 'agility'), ('intellect', 'intellect'), ('charisma', 'charisma')], max_length=50)),
                ('base_difficulty', models.IntegerField(default=10)),
                ('allow_abort', models.BooleanField(default=False)),
                ('approach', models.ForeignKey(blank=True, help_text='Optional approach-specific variant; commonly used for Beat 2 branching.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beat_variants', to='game.jobapproach')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beat_variants', to='game.job')),
            ],
            options={
                'ordering': ['job', 'beat_number', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='JobRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('recon', 'Recon'), ('contact', 'Contact')], default='recon', max_length=20)),
                ('recon_tier', models.CharField(choices=[('low', 'Low'), ('mid', 'Mid'), ('high', 'High')], default='low', max_length=10)),
                ('current_beat', models.PositiveSmallIntegerField(default=0)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('aborted', 'Aborted')], default='active', max_length=20)),
                ('beat_1_success', models.BooleanField(blank=True, null=True)),
                ('beat_2_success', models.BooleanField(blank=True, null=True)),
                ('cash_awarded', models.IntegerField(default=0)),
                ('heat_applied', models.IntegerField(default=0)),
                ('rep_awarded', models.IntegerField(default=0)),
                ('started_turn', models.PositiveIntegerField(default=0)),
                ('completed_turn', models.PositiveIntegerField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('contact_offer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runs', to='game.contactjoboffer')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='game.job')),
                ('selected_approach', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runs', to='game.jobapproach')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_runs', to='game.gamesession')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='PlayerContactOfferState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cooldown_until_turn', models.PositiveIntegerField(default=0)),
                ('met_contact', models.BooleanField(default=False)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_states', to='game.contactjoboffer')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_offer_states', to='game.gamesession')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerJobState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_count', models.PositiveIntegerField(default=0)),
                ('cooldown_until_turn', models.PositiveIntegerField(default=0)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_states', to='game.job')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_states', to='game.gamesession')),
            ],
        ),
        migrations.AddConstraint(
            model_name='contactjoboffer',
            constraint=models.UniqueConstraint(fields=('contact', 'job'), name='uq_contactjoboffer_contact_job'),
        ),
        migrations.AddConstraint(
            model_name='jobapproach',
            constraint=models.UniqueConstraint(fields=('job', 'key'), name='uq_jobapproach_job_key'),
        ),
        migrations.AddConstraint(
            model_name='jobbeatvariant',
            constraint=models.UniqueConstraint(fields=('job', 'beat_number', 'key'), name='uq_jobbeatvariant_job_beat_key'),
        ),
        migrations.AddConstraint(
            model_name='playercontactofferstate',
            constraint=models.UniqueConstraint(fields=('session', 'offer'), name='uq_playercontactofferstate_session_offer'),
        ),
        migrations.AddConstraint(
            model_name='playerjobstate',
            constraint=models.UniqueConstraint(fields=('session', 'job'), name='uq_playerjobstate_session_job'),
        ),
    ]
