# Generated by Django 6.0.4 on 2026-04-25 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0043_combatstate_pending_enemy_attack_json'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='completedquest',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='playercontact',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='playergangstanding',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='playerinventory',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='completedquest',
            constraint=models.UniqueConstraint(fields=('session', 'quest'), name='uq_completedquest_session_quest'),
        ),
        migrations.AddConstraint(
            model_name='playercontact',
            constraint=models.UniqueConstraint(fields=('session', 'contact'), name='uq_playercontact_session_contact'),
        ),
        migrations.AddConstraint(
            model_name='playergangstanding',
            constraint=models.UniqueConstraint(fields=('session', 'gang'), name='uq_playergangstanding_session_gang'),
        ),
        migrations.AddConstraint(
            model_name='playerinventory',
            constraint=models.UniqueConstraint(fields=('session', 'item'), name='uq_playerinventory_session_item'),
        ),
    ]
