# Generated by Django 6.0.4 on 2026-04-26 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0047_remove_quest_scenes_m2m'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
