# Generated by Django 6.0.4 on 2026-04-26

from django.db import migrations, models
from django.utils.text import slugify


def _populate_property_keys(apps, schema_editor):
    Property = apps.get_model("game", "Property")
    used_keys = set(
        Property.objects.exclude(key__isnull=True).exclude(key="").values_list("key", flat=True)
    )
    for prop in Property.objects.all().order_by("id"):
        if prop.key:
            used_keys.add(prop.key)
            continue
        base = slugify(prop.name) or "property"
        candidate = base
        suffix = 2
        while candidate in used_keys:
            candidate = f"{base}-{suffix}"
            suffix += 1
        prop.key = candidate
        prop.save(update_fields=["key"])
        used_keys.add(candidate)


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0050_backfill_requirementgroup_scopes"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="key",
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.RunPython(_populate_property_keys, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="property",
            name="key",
            field=models.SlugField(unique=True),
        ),
    ]
