# Generated by Django 6.0.4 on 2026-05-04 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0062_remove_rival_claims_schema'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='requirementgroup',
            name='uq_requirement_group_scoped_identity',
        ),
        migrations.AlterField(
            model_name='choice',
            name='clear_flag_name',
            field=models.CharField(blank=True, help_text='If set, this flag is cleared from the session when this choice is taken. Use a registered key or supported dynamic pattern.', max_length=100),
        ),
        migrations.AlterField(
            model_name='choice',
            name='set_flag_name',
            field=models.CharField(blank=True, help_text='If set, this flag is set on the session when this choice is taken. Use a registered key or supported dynamic pattern.', max_length=100),
        ),
        migrations.AddConstraint(
            model_name='requirementgroup',
            constraint=models.UniqueConstraint(condition=models.Q(('scope_type__isnull', False), ('scope_key__isnull', False), ('group_key__isnull', False)), fields=('scope_type', 'scope_key', 'group_key'), name='uq_requirement_group_scoped_identity'),
        ),
    ]
