# Generated by Django 6.0.4 on 2026-05-09 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0063_remove_requirementgroup_uq_requirement_group_scoped_identity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventlog',
            name='batch_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
